services:
  api:
    build: ./hello-world-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      mongo:
        condition: service_started
    environment:
      MONGO_URL: mongodb://mongo:27017/
  mongo:
    image: "mongo:8.0.4"
    restart: always
  mongo-express:
    image: mongo-express:1.0-20
    restart: always
    depends_on:
      mongo:
        condition: service_started
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
