- name: Setup docker on the vm
  hosts: all
  remote_user: root
  vars:
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
  tasks:
    - name: Uninstall conflicting packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl

    - name: Add repository key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add repository source
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ deb_architecture[ansible_architecture] }}]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
